In [1]:
import pandas as pd
import numpy as np

data = {
    'Hoc_Vien': ['An', 'Bình', 'Cường', 'Dũng', 'Em'],
    'Diem_Giua_Ky': [8.0, np.nan, 7.5, 9.0, np.nan], # Bình và Em vắng thi
    'Diem_Cuoi_Ky': [8.5, 7.0, 8.0, np.nan, 6.5],    # Dũng vắng thi
    'Feedback': ['Tốt', 'Bình thường', np.nan, 'Rất tốt', np.nan] # Không chịu điền form
}

df_lms = pd.DataFrame(data)
print("--- 1. BẢNG DỮ LIỆU GỐC (Lỗ chỗ NaN) ---")
display(df_lms)

--- 1. BẢNG DỮ LIỆU GỐC (Lỗ chỗ NaN) ---

  Hoc_Vien  Diem_Giua_Ky  Diem_Cuoi_Ky     Feedback
0       An           8.0           8.5          Tốt
1     Bình           NaN           7.0  Bình thường
2    Cường           7.5           8.0          NaN
3     Dũng           9.0           NaN      Rất tốt
4       Em           NaN           6.5          NaN

In [ ]:
print("\n--- 2. KHÁM BỆNH (DÒ MÌN) ---")
# Hàm .isna().sum() là combo kinh điển để đếm xem mỗi cột có bao nhiêu ô trống
print(df_lms.isna().sum())

In [ ]:
print("\n--- 3. CÁCH 1: XÓA BỎ (DROP) ---")
df_xoa = df_lms.dropna()        # Cần cân nhắc vì sẽ xóa hết các dòng trống
print(df_xoa)

--- 3. CÁCH 1: XÓA BỎ (DROP) ---
  Hoc_Vien  Diem_Giua_Ky  Diem_Cuoi_Ky Feedback
0       An           8.0           8.5      Tốt

In [4]:
print("\n--- 4. CÁCH 2: LẤP ĐẦY (FILL) - TƯ DUY SENIOR ---")

df_fill = df_lms.copy()

# Tình huống 1: Vắng thi -> Cho 0 điểm
df_fill['Diem_Giua_Ky'] = df_fill['Diem_Giua_Ky'].fillna(0)
df_fill['Diem_Cuoi_Ky'] = df_fill['Diem_Cuoi_Ky'].fillna(0)

# Tình huống 2: Cột Text (Feedback) -> Điền chữ mặc định
df_fill['Feedback'] = df_fill['Feedback'].fillna('Khong Y Kien')
display(df_fill)

--- 4. CÁCH 2: LẤP ĐẦY (FILL) - TƯ DUY SENIOR ---

  Hoc_Vien  Diem_Giua_Ky  Diem_Cuoi_Ky      Feedback
0       An           8.0           8.5           Tốt
1     Bình           0.0           7.0   Bình thường
2    Cường           7.5           8.0  Khong Y Kien
3     Dũng           9.0           0.0       Rất tốt
4       Em           0.0           6.5  Khong Y Kien

In [ ]:
df_pos = pd.DataFrame({
    'Mon': ['Cafe Den', 'Tra Dao', 'Bac Xiu', 'Cafe Den', 'Tra Dao'],
    'Gia': [20, 30, 35, 20, 30],
    'So_Luong': [5, np.nan, 3, np.nan, 10]
})

tong_so_luong = df_pos['So_Luong'].mean()

df_fill = df_pos.copy()
df_fill['So_Luong'] = df_fill['So_Luong'].fillna(tong_so_luong)
display(df_fill)